
   
name: Issues Notifier
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Work Weixin Notifier
        uses: jerray/work-weixin-notifier@v1.1.0
        with:
          key: ${{ secrets.weixin_bot_key }}
          content: '文档issues有更新，请前往查看：${{ github.event.issue.html_url }} ${{ github.Repository }} ${{ github.event.issue.number }} @ostwindli'
          type: markdown
          status: ${{ job.status }}
